version: "3.9"
services:
  analytics:
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      PGHOST: storage
      PGPORT: 5432
      PGDATABASE: analytics
      PGUSER: postgres
      PGPASSWORD: password
    ports:
      - "3000:3000"
    image: "jeblanchard/personal-website:analytics"

  storage:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/
    ports:
      - "5432:5432"
