version: "3.9"
services:
  analytics:
    build: .
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: site-statistics
      PGUSER: postgres
      PGPASSWORD: password
    ports:
      - "3000:3000"
    image: "jeblanchard/personal-website:analytics"

  storage:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/
    volumes:
      - site-data:/data/
    ports:
      - "5432:5432"

volumes:
  site-data:
