#! /bin/bash

printf "Enter the ID of the container you'd like to\nsave the dump of.\n\n"

read -r container_id
container_dump_filepath="./cluster_dump"

# relative to the root of the project
host_dump_filepath="./data/cluster_dump"

# generate DB dump and save it to the container file system
docker exec "$container_id" sh -c "pg_dumpall -U postgres -f $container_dump_filepath"

# copy dump and save it to the host file system (this project)
docker cp "$container_id":$container_dump_filepath "$host_dump_filepath"

# delete DB dump from the container file system
docker exec "$container_id" sh -c "rm $container_dump_filepath"

printf "\nSuccessfully saved DB cluster dump to %s" "$host_dump_filepath"
